# ref: https://forum.typst.app/t/publish-example-pdfs-using-github-pages/5781
name: Publish Resume

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: typst-community/setup-typst@v4
        with:
          typst-version: latest

      - name: create output directory
        run: mkdir github-pages-temp

      - name: setup font
        run: |
          sudo apt update -y
          sudo apt install fonts-liberation -y

      - name: build copile
        run: typst compile resume.typ github-pages-temp/resume.pdf

      - name: upload site files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages-temp

  # See https://github.com/actions/deploy-pages
  deploy-site:
    needs: build-site

    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
